"""WARNING: Generated by Claude. AI Slop, but it works."""

bl_info = {
    "name": "VSE Ripple Cut (Resolve-style)",
    "author": "Generated by Claude",
    "version": (2, 3, 0),
    "blender": (5, 2, 0),
    "location": "Video Sequencer > Strip menu, right-click menu, Ctrl+X, Ctrl+Shift+[ / ]",
    "description": "Ripple cut, ripple trim to playhead and range ripple delete for the VSE",
    "category": "Sequencer",
}

import bpy
from bpy.props import BoolProperty, EnumProperty

RIPPLE_DELETE_KEY = ("X", {"shift": True})
RIPPLE_CUT_KEY = ("X", {"ctrl": True})
RIPPLE_RANGE_KEY = ("X", {"ctrl": True, "shift": True})
RIPPLE_CUT_LEFT_KEY = ("LEFT_BRACKET", {"ctrl": True, "shift": True})
RIPPLE_CUT_RIGHT_KEY = ("RIGHT_BRACKET", {"ctrl": True, "shift": True})
ADD_KEYMAPS = True

_OVERLAP_HINT = "Press F9 and turn off All Channels, or unlock/move those strips"


def _all_channels_prop():
    return BoolProperty(
        name="All Channels",
        description=(
            "Ripple every channel, like Resolve. Turn off to ripple only the "
            "channels the removed strips were on, which helps when a music bed "
            "or title spans the whole timeline"
        ),
        default=True,
    )


def _ripple_markers_prop():
    return BoolProperty(
        name="Ripple Markers",
        description=(
            "Also shift timeline markers sitting after the removed material. "
            "Ignored when All Channels is off"
        ),
        default=False,
    )


def _container(context):
    ed = context.scene.sequence_editor
    if ed is None:
        return None
    target = ed.meta_stack[-1] if len(ed.meta_stack) else ed
    if hasattr(target, "strips"):
        return target.strips
    return getattr(target, "sequences", None)


def _derived(strip):
    return getattr(strip, "input_1", None) is not None


def _shiftable(strip):
    return not strip.lock and not _derived(strip)


def _merge_spans(spans):
    merged = []
    for start, end in sorted(spans):
        if merged and start <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end])
    return merged


def _offset_at(frame, spans):
    return sum(end - start for start, end in spans if end <= frame)


def _plan_shifts(strips, spans, channels=None):
    plan, blocked = [], []
    for strip in strips:
        if channels is not None and strip.channel not in channels:
            continue
        delta = _offset_at(strip.left_handle, spans)
        if delta <= 0:
            continue
        if _shiftable(strip):
            plan.append((strip, -delta))
        elif not _derived(strip):
            blocked.append(strip.name)
    return plan, blocked


def _overlaps(layout):
    by_channel = {}
    for name, channel, start, end in layout:
        by_channel.setdefault(channel, []).append((start, end, name))

    pairs = set()
    for items in by_channel.values():
        items.sort()
        reach_end, reach_name = None, None
        for start, end, name in items:
            if reach_end is not None and start < reach_end:
                pairs.add(frozenset((reach_name, name)))
            if reach_end is None or end > reach_end:
                reach_end, reach_name = end, name
    return pairs


def _new_overlaps(before, after):
    return _overlaps(after) - _overlaps(before)


def _apply_shifts(plan):
    for strip, delta in sorted(plan, key=lambda item: item[0].left_handle):
        strip.content_start += delta


def _shift_markers(scene, spans):
    for marker in scene.timeline_markers:
        marker.frame -= _offset_at(marker.frame, spans)


def _describe(pairs, limit=2):
    names = sorted(" / ".join(sorted(pair)) for pair in pairs)
    text = "; ".join(names[:limit])
    if len(names) > limit:
        text += f"; and {len(names) - limit} more"
    return text


def _copy_selection(context):
    area = context.area
    if area is not None and area.type == "SEQUENCE_EDITOR":
        try:
            return "FINISHED" in bpy.ops.sequencer.copy()
        except RuntimeError:
            return False

    screen = getattr(context, "screen", None)
    if screen is None:
        return False
    area = next((a for a in screen.areas if a.type == "SEQUENCE_EDITOR"), None)
    if area is None:
        return False
    region = next((r for r in area.regions if r.type == "WINDOW"), None)
    try:
        with context.temp_override(area=area, region=region,
                                   space_data=area.spaces.active):
            return "FINISHED" in bpy.ops.sequencer.copy()
    except (RuntimeError, TypeError):
        return False


def _prepare_ripple(operator, context, all_channels):
    strips = _container(context)
    if strips is None:
        operator.report({"ERROR"}, "No sequencer data")
        return None

    selected = [s for s in strips if s.select]
    if not selected:
        operator.report({"ERROR"}, "Nothing selected")
        return None

    locked = sorted(s.name for s in selected if s.lock)
    if locked:
        operator.report({"ERROR"},
                        "Locked strip(s) in the selection: " + ", ".join(locked[:3]))
        return None

    spans = _merge_spans([(s.left_handle, s.right_handle) for s in selected])
    channels = None if all_channels else {s.channel for s in selected}
    survivors = [s for s in strips if not s.select and not _derived(s)]

    plan, blocked = _plan_shifts(survivors, spans, channels)
    deltas = {strip.name: delta for strip, delta in plan}

    before = [(s.name, s.channel, s.left_handle, s.right_handle) for s in survivors]
    after = [(name, channel, start + deltas.get(name, 0), end + deltas.get(name, 0))
             for name, channel, start, end in before]

    clashes = _new_overlaps(before, after)
    if clashes:
        operator.report({"ERROR"},
                        f"Ripple would overlap {_describe(clashes)}. {_OVERLAP_HINT}")
        return None

    return spans, deltas, blocked, len(selected)


def _commit_ripple(operator, context, prepared, ripple_markers, all_channels):
    spans, deltas, blocked, _count = prepared

    try:
        result = bpy.ops.sequencer.delete()
    except RuntimeError as exc:
        operator.report({"ERROR"}, f"Delete failed: {exc}")
        return False
    if "FINISHED" not in result:
        operator.report({"ERROR"}, "Delete was refused by Blender")
        return False

    strips = _container(context)
    live = {s.name: s for s in strips}
    _apply_shifts([(live[name], delta)
                   for name, delta in deltas.items() if name in live])

    if ripple_markers and all_channels:
        _shift_markers(context.scene, spans)

    if blocked:
        operator.report({"WARNING"},
                        f"{len(blocked)} locked strip(s) stayed put: "
                        + ", ".join(blocked[:3]))
    return True


class RIPPLECUT_OT_delete(bpy.types.Operator):
    """Delete the selected strips and close the gap"""

    bl_idname = "ripplecut.delete"
    bl_label = "Ripple Delete"
    bl_options = {"REGISTER", "UNDO"}

    all_channels: _all_channels_prop()
    ripple_markers: _ripple_markers_prop()

    @classmethod
    def poll(cls, context):
        strips = _container(context)
        return strips is not None and any(s.select for s in strips)

    def execute(self, context):
        prepared = _prepare_ripple(self, context, self.all_channels)
        if prepared is None:
            return {"CANCELLED"}
        if not _commit_ripple(self, context, prepared,
                              self.ripple_markers, self.all_channels):
            return {"CANCELLED"}
        return {"FINISHED"}


class RIPPLECUT_OT_cut(bpy.types.Operator):
    """Copy the selected strips to the clipboard, delete them and close the gap"""

    bl_idname = "ripplecut.cut"
    bl_label = "Ripple Cut"
    bl_options = {"REGISTER", "UNDO"}

    all_channels: _all_channels_prop()
    ripple_markers: _ripple_markers_prop()

    @classmethod
    def poll(cls, context):
        strips = _container(context)
        return strips is not None and any(s.select for s in strips)

    def execute(self, context):
        prepared = _prepare_ripple(self, context, self.all_channels)
        if prepared is None:
            return {"CANCELLED"}

        count = prepared[3]
        copied = _copy_selection(context)

        if not _commit_ripple(self, context, prepared,
                              self.ripple_markers, self.all_channels):
            return {"CANCELLED"}

        if copied:
            self.report({"INFO"}, f"Ripple cut {count} strip(s) - Ctrl+V to paste")
        else:
            self.report({"WARNING"}, "Rippled, but the clipboard copy failed")
        return {"FINISHED"}


class RIPPLECUT_OT_trim_playhead(bpy.types.Operator):
    """Remove one end of a strip at the playhead and close the gap"""

    bl_idname = "ripplecut.trim_playhead"
    bl_label = "Ripple Cut to Playhead"
    bl_options = {"REGISTER", "UNDO"}

    side: EnumProperty(
        name="Side",
        items=(
            ("LEFT", "Left", "Remove from the strip's start up to the playhead"),
            ("RIGHT", "Right", "Remove from the playhead to the strip's end"),
        ),
        default="RIGHT",
    )
    all_channels: _all_channels_prop()
    ripple_markers: _ripple_markers_prop()

    @classmethod
    def poll(cls, context):
        return _container(context) is not None

    def _amount(self, strip, playhead):
        if self.side == "LEFT":
            return playhead - strip.left_handle
        return strip.right_handle - playhead

    def execute(self, context):
        scene = context.scene
        playhead = scene.frame_current
        strips = _container(context)
        if strips is None:
            self.report({"ERROR"}, "No sequencer data")
            return {"CANCELLED"}

        under = [s for s in strips
                 if _shiftable(s) and s.left_handle < playhead < s.right_handle]
        if not under:
            self.report({"ERROR"}, "Playhead is not inside an editable strip")
            return {"CANCELLED"}

        candidates = sorted((s for s in under if s.select), key=lambda s: (-s.channel, s.name))
        if not candidates:
            candidates = sorted(under, key=lambda s: (-s.channel, s.name))

        active = context.scene.sequence_editor.active_strip
        ref = active if active in candidates else candidates[0]

        amount = self._amount(ref, playhead)
        if amount < 1:
            self.report({"ERROR"}, "Nothing to trim at the playhead")
            return {"CANCELLED"}

        matched = [s for s in candidates if self._amount(s, playhead) == amount]
        matched_names = {s.name for s in matched}
        skipped = len(candidates) - len(matched)

        if self.side == "LEFT":
            spans = [[ref.left_handle, playhead]]
        else:
            spans = [[playhead, ref.right_handle]]
        channels = None if self.all_channels else {s.channel for s in matched}

        others = [s for s in strips
                  if s.name not in matched_names and not _derived(s)]
        plan, blocked = _plan_shifts(others, spans, channels)
        deltas = {strip.name: delta for strip, delta in plan}

        before, after = [], []
        for strip in others:
            delta = deltas.get(strip.name, 0)
            before.append((strip.name, strip.channel,
                           strip.left_handle, strip.right_handle))
            after.append((strip.name, strip.channel,
                          strip.left_handle + delta, strip.right_handle + delta))
        for strip in matched:
            before.append((strip.name, strip.channel,
                           strip.left_handle, strip.right_handle))
            if self.side == "LEFT":
                after.append((strip.name, strip.channel,
                              strip.left_handle, strip.right_handle - amount))
            else:
                after.append((strip.name, strip.channel, strip.left_handle, playhead))

        clashes = _new_overlaps(before, after)
        if clashes:
            self.report({"ERROR"},
                        f"Ripple would overlap {_describe(clashes)}. {_OVERLAP_HINT}")
            return {"CANCELLED"}

        new_playhead = spans[0][0]
        for strip in sorted(matched, key=lambda s: s.left_handle):
            if self.side == "LEFT":
                strip.left_handle = playhead
                strip.content_start -= amount
            else:
                strip.right_handle = playhead

        _apply_shifts(plan)

        if self.ripple_markers and self.all_channels:
            _shift_markers(scene, spans)
        if self.side == "LEFT":
            scene.frame_current = new_playhead

        msg = f"Rippled {len(matched)} strip(s) by {amount} frame(s)"
        if skipped:
            msg += f", skipped {skipped} with a different trim length"
        if blocked:
            msg += f", {len(blocked)} locked strip(s) stayed put"
        self.report({"WARNING"} if (skipped or blocked) else {"INFO"}, msg)
        return {"FINISHED"}


class RIPPLECUT_OT_delete_range(bpy.types.Operator):
    """Remove everything inside the preview range on every channel and close the gap"""

    bl_idname = "ripplecut.delete_range"
    bl_label = "Ripple Delete Range"
    bl_options = {"REGISTER", "UNDO"}

    copy_first: BoolProperty(
        name="Copy to Clipboard",
        description="Copy the removed strips before deleting them",
        default=False,
    )
    all_channels: _all_channels_prop()
    ripple_markers: _ripple_markers_prop()

    @classmethod
    def poll(cls, context):
        return _container(context) is not None

    @staticmethod
    def _split_all(frame):
        try:
            bpy.ops.sequencer.select_all(action="SELECT")
            bpy.ops.sequencer.split(frame=frame, type="SOFT", side="RIGHT")
        except RuntimeError:
            return False
        return True

    def execute(self, context):
        scene = context.scene

        if not scene.use_preview_range:
            self.report({"ERROR"},
                        "No preview range. Select strips and press Ctrl+P, "
                        "or set it manually")
            return {"CANCELLED"}

        start = scene.frame_preview_start
        end = scene.frame_preview_end + 1
        if end - start < 1:
            self.report({"ERROR"}, "Preview range is empty")
            return {"CANCELLED"}

        strips = _container(context)
        if strips is None:
            self.report({"ERROR"}, "No sequencer data")
            return {"CANCELLED"}

        range_channels = {s.channel for s in strips
                          if s.left_handle < end and s.right_handle > start}
        frozen = sorted(s.name for s in strips
                        if s.lock and s.right_handle > start
                        and (self.all_channels or s.channel in range_channels))
        if frozen:
            self.report({"ERROR"},
                        "Locked strip(s) at or after the range: "
                        + ", ".join(frozen[:3]) + ". Unlock them first")
            return {"CANCELLED"}

        for index, frame in enumerate((start, end)):
            if not self._split_all(frame):
                self.report({"ERROR"}, "Split failed - needs an active sequencer")
                return {"FINISHED"} if index else {"CANCELLED"}

        strips = _container(context)
        inside = 0
        for strip in strips:
            hit = (start <= strip.left_handle and strip.right_handle <= end
                   and not _derived(strip))
            strip.select = hit
            strip.select_left_handle = False
            strip.select_right_handle = False
            inside += int(hit)

        if not inside:
            self.report({"INFO"}, "Nothing inside the preview range")
            return {"FINISHED"}

        prepared = _prepare_ripple(self, context, self.all_channels)
        if prepared is None:
            return {"FINISHED"}

        if self.copy_first and not _copy_selection(context):
            self.report({"WARNING"}, "Clipboard copy failed")

        if not _commit_ripple(self, context, prepared,
                              self.ripple_markers, self.all_channels):
            return {"FINISHED"}

        scene.frame_preview_start = start
        scene.frame_preview_end = start
        return {"FINISHED"}


_MENUS = ("SEQUENCER_MT_strip", "SEQUENCER_MT_context_menu")
_CLASSES = (RIPPLECUT_OT_delete, RIPPLECUT_OT_cut,
            RIPPLECUT_OT_trim_playhead, RIPPLECUT_OT_delete_range)
_keymaps = []


def _menu_draw(self, context):
    layout = self.layout
    layout.separator()
    layout.operator(RIPPLECUT_OT_delete.bl_idname)
    layout.operator(RIPPLECUT_OT_cut.bl_idname)
    op = layout.operator(RIPPLECUT_OT_trim_playhead.bl_idname,
                         text="Ripple Cut Left (Start to Playhead)")
    op.side = "LEFT"
    op = layout.operator(RIPPLECUT_OT_trim_playhead.bl_idname,
                         text="Ripple Cut Right (Playhead to End)")
    op.side = "RIGHT"
    layout.operator(RIPPLECUT_OT_delete_range.bl_idname)


def _clear_menu_draws():
    for name in _MENUS:
        menu = getattr(bpy.types, name, None)
        if menu is None:
            continue
        try:
            funcs = menu._dyn_ui_initialize()
        except Exception:
            continue
        for func in list(funcs):
            if getattr(func, "__name__", "") == "_menu_draw":
                funcs.remove(func)


def register():
    if bpy.app.version[:2] != (5, 2):
        print("VSE Ripple Cut: built for Blender 5.2 LTS, running on "
              f"{bpy.app.version_string} - the sequencer API may differ")

    for cls in _CLASSES:
        stale = getattr(bpy.types, cls.__name__, None)
        if stale is not None:
            try:
                bpy.utils.unregister_class(stale)
            except Exception:
                pass
        bpy.utils.register_class(cls)

    _clear_menu_draws()
    for name in _MENUS:
        menu = getattr(bpy.types, name, None)
        if menu is not None:
            menu.append(_menu_draw)

    _keymaps.clear()
    if not ADD_KEYMAPS:
        return
    kc = bpy.context.window_manager.keyconfigs.addon
    if kc is None:
        return
    km = kc.keymaps.new(name="Sequencer", space_type="SEQUENCE_EDITOR")

    bindings = (
        (RIPPLECUT_OT_delete.bl_idname, RIPPLE_DELETE_KEY, {}),
        (RIPPLECUT_OT_cut.bl_idname, RIPPLE_CUT_KEY, {}),
        (RIPPLECUT_OT_delete_range.bl_idname, RIPPLE_RANGE_KEY, {}),
        (RIPPLECUT_OT_trim_playhead.bl_idname, RIPPLE_CUT_LEFT_KEY, {"side": "LEFT"}),
        (RIPPLECUT_OT_trim_playhead.bl_idname, RIPPLE_CUT_RIGHT_KEY, {"side": "RIGHT"}),
    )
    for idname, (key, mods), props in bindings:
        for item in [i for i in km.keymap_items
                     if i.idname == idname and i.type == key]:
            km.keymap_items.remove(item)
        kmi = km.keymap_items.new(idname, key, "PRESS", **mods)
        for prop, value in props.items():
            setattr(kmi.properties, prop, value)
        _keymaps.append((km, kmi))


def unregister():
    for km, kmi in _keymaps:
        try:
            km.keymap_items.remove(kmi)
        except Exception:
            pass
    _keymaps.clear()

    _clear_menu_draws()

    for cls in reversed(_CLASSES):
        try:
            bpy.utils.unregister_class(cls)
        except Exception:
            pass


if __name__ == "__main__":
    register()
