{
  flake.nixosModules.laptopHardware = { config, lib, pkgs, modulesPath, ... }: {
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];
  
    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];
  
    fileSystems."/" =
      { device = "/dev/disk/by-uuid/aff619fb-7337-4cae-9e6a-84e9eb2660cc";
        fsType = "btrfs";
        options = [ "subvol=root" ];
      };
  
    fileSystems."/home" =
      { device = "/dev/disk/by-uuid/aff619fb-7337-4cae-9e6a-84e9eb2660cc";
        fsType = "btrfs";
        options = [ "subvol=home" ];
      };
  
    fileSystems."/nix" =
      { device = "/dev/disk/by-uuid/aff619fb-7337-4cae-9e6a-84e9eb2660cc";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
      };
  
    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/B302-4215";
        fsType = "vfat";
        options = [ "fmask=0022" "dmask=0022" ];
      };
  
    fileSystems."/swap" =
      { device = "/dev/disk/by-uuid/aff619fb-7337-4cae-9e6a-84e9eb2660cc";
        fsType = "btrfs";
        options = [ "subvol=swap" ];
      };
  
    swapDevices = [ ];
  
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
